### ISSUE TITLE
Push python patch generation to a separate pypcpatch module

### ISSUE THREAD

**Issue by vpicavet** [LI3DS/fdw-li3ds#2]
We will need some more pcpatch python code at some point, so we should write a module dedicated for this.

We can base this work on what @Remi-C has already done in https://github.com/Remi-C/PPPP_utilities/tree/master/pointcloud
@dustymugs also has some code to refactor here : https://github.com/dustymugs/pgpointcloud_utils

**Comment by Remi-C** [comment]
fiy, dustymug is BBorie which is well known on postgis mailing list.

Feature of my implementation:
- safe to be used outside of postgres, or inside (plpythonu)
- fast conversion to numpy
  (with ign computer, several hundred of millions points/hour for read
  patch->numpy-> write patch)
- get schema if it doesn't have it, use a schema caching mechanism
- optionnal offset/scale
- optionnal list of dimension of interest to only get those (faster, less
  memory)
- object python

the limitation of my implementation are
- need uncompressed patch
- no error management
- break if you put funky string into schema description (couldn't solve
  this one in python 2.7)
- only python 2.7 and not 3.2
- no systematic testing (would need unittest)
- no consistent doc
- ...

there are 2 levels of getting point to patch:
- 1stlevel : convert pcpatch to numpy spec array , each dimension
  conserves its type (or closest type python can understand)
- 2nd level: convert pcpatch to numpy double array (using offset/scale
  optionnaly), which is in practice the most useful one.

same for points -> patch

keep me posted, I'd really like to have a better python lib. for
pgpointcloud
(it could use cython, or directly pgpointcloud c lib with bindings, I tried
that and failed)
Rémi

2016-02-26 14:46 GMT+01:00 Vincent Picavet notifications@github.com:

**Comment by elemoine** [comment]
There are good ideas in there, but I think we can close this. We will possibly revisit this later.
