### ISSUE TITLE
echopulse results

### ISSUE THREAD

**Issue by vpicavet** [LI3DS/fdw-li3ds#3]
echopulse FDW should return : 
- a PCPatch column for pulses
- a PCPatch column for echoes corresponding to the pulses

2 options here : 
- we just insert the data sorted, and we keep the amount of echoes for each pulse ( like in the original data )
- we want to avoid the "sorted" hypothesis for the relation between the two, therefore we store for each echo the corresponding pulse and the order of the echo

The best solution has to be defined.
Some queries we regularly do : 
- Find the latest echo for a pulse
- Find the number of echoes for a pulse
- .. add your own ...

**Comment by ldgeo** [comment]
No more needed since we want pulse and echo signal in a single patch.
